import Footer from "@/components/Footer";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Menu from "@/components/Menu";

export const metadata = {
  title: "MBT Admin Panel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-main-bg bg-no-repeat">
        <Navbar />
        <div className="flex">
          <div>
            <Menu />
          </div>
          <div className="pl-7">
            <main>{children}</main>
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
